export interface Product {
  id: number;
  category: string;
  brand: string;
  name: string;
  volume: string;
  retailPrice: number;
  description: string;
  tags: string[];
}

export const products: Product[] = [
  {
    id: 1,
    category: "SPF",
    brand: "Beauty of Joseon",
    name: "Relief Sun: Rice + Probiotics SPF50+ PA++++",
    volume: "50ml",
    retailPrice: 33.12,
    description: "Viral TikTok SPF #1 globally. No white cast, rice extract brightens while probiotics strengthen the skin barrier. Perfect for Somalia's high-UV climate.",
    tags: ["SPF 50+", "No White Cast", "K-Beauty", "Brightening"],
  },
  {
    id: 2,
    category: "SPF",
    brand: "COSRX",
    name: "Aloe Soothing Sun Cream SPF50 PA+++",
    volume: "50ml",
    retailPrice: 24.51,
    description: "Best-selling K-beauty SPF with soothing aloe vera. Ideal for hot climates, leaves skin feeling calm and protected all day.",
    tags: ["SPF 50+", "Soothing", "Aloe", "K-Beauty"],
  },
  {
    id: 3,
    category: "SPF",
    brand: "La Roche-Posay",
    name: "Anthelios UVMune 400 Invisible Fluid SPF50+",
    volume: "50ml",
    retailPrice: 25.88,
    description: "Dermatologist gold-standard SPF trusted globally. Invisible finish with advanced UVMune 400 technology for superior UV protection.",
    tags: ["SPF 50+", "Invisible", "Dermatologist", "Premium"],
  },
  {
    id: 4,
    category: "SPF",
    brand: "COSRX",
    name: "The Ultra-Light Invisible Sunscreen SPF50 PA++++",
    volume: "50ml",
    retailPrice: 27.78,
    description: "Invisible finish perfect for oily and combination skin in warm, humid weather. Lightweight formula that never feels greasy.",
    tags: ["SPF 50+", "Ultra-Light", "Oily Skin", "K-Beauty"],
  },
  {
    id: 5,
    category: "SPF",
    brand: "Abib",
    name: "Quick Sunstick Protection Bar SPF50+ PA++++",
    volume: "22g",
    retailPrice: 33.57,
    description: "Convenient stick SPF for easy reapplication outdoors. Travel-friendly format perfect for on-the-go sun protection throughout the day.",
    tags: ["SPF 50+", "Stick Format", "Travel-Friendly", "K-Beauty"],
  },
  {
    id: 6,
    category: "SPF",
    brand: "SKIN1004",
    name: "Centella Hyalu-Cica Water-Fit Sun Serum SPF50+",
    volume: "50ml",
    retailPrice: 32.70,
    description: "Serum-texture SPF combining centella asiatica and hyaluronic acid for soothing hydration alongside sun protection. A trending formula for sensitive skin.",
    tags: ["SPF 50+", "Serum Texture", "Centella", "Hydrating"],
  },
  {
    id: 7,
    category: "SPF",
    brand: "Anua",
    name: "Heartleaf Silky Moisture Sunscreen SPF50+ PA+++",
    volume: "50ml",
    retailPrice: 36.78,
    description: "Silky, non-greasy finish sunscreen powered by heartleaf extract. Anua's momentum is growing globally as a go-to clean K-beauty brand.",
    tags: ["SPF 50+", "Silky Finish", "Heartleaf", "K-Beauty"],
  },
  {
    id: 8,
    category: "SPF",
    brand: "medicube",
    name: "Collagen Firming Sun Cream SPF50+",
    volume: "50ml",
    retailPrice: 32.82,
    description: "Anti-aging SPF crossover combining collagen-firming benefits with SPF 50+ protection. Clinical brand positioning for results-driven skincare.",
    tags: ["SPF 50+", "Anti-Aging", "Collagen", "Clinical"],
  },
  {
    id: 9,
    category: "Essence",
    brand: "COSRX",
    name: "Advanced Snail 96 Mucin Power Essence",
    volume: "100ml",
    retailPrice: 33.12,
    description: "Amazon #1 K-beauty essence with 200K+ reviews worldwide. 96% snail secretion filtrate repairs and hydrates for glass-skin results.",
    tags: ["Snail Mucin", "Repairing", "Bestseller", "K-Beauty"],
  },
  {
    id: 10,
    category: "Serum",
    brand: "The Ordinary",
    name: "Niacinamide 10% + Zinc 1%",
    volume: "60ml",
    retailPrice: 22.88,
    description: "#1 serum globally with unbeatable price-to-performance. Minimizes pores, controls oil, and fades dark spots and hyperpigmentation.",
    tags: ["Niacinamide", "Pore Care", "Brightening", "Oil Control"],
  },
  {
    id: 11,
    category: "Serum",
    brand: "The Ordinary",
    name: "Hyaluronic Acid 2% + B5",
    volume: "30ml",
    retailPrice: 19.07,
    description: "Top 5 Amazon global skincare staple. Multi-weight hyaluronic acid with vitamin B5 for deep, lasting hydration at every skin layer.",
    tags: ["Hyaluronic Acid", "Hydrating", "Plumping", "Vitamin B5"],
  },
  {
    id: 12,
    category: "Serum",
    brand: "Beauty of Joseon",
    name: "Glow Serum: Propolis + Niacinamide",
    volume: "30ml",
    retailPrice: 39.23,
    description: "Viral K-beauty brightening hero. Propolis soothes and repairs while niacinamide brightens and evens skin tone for a radiant glow.",
    tags: ["Brightening", "Propolis", "Niacinamide", "K-Beauty"],
  },
  {
    id: 13,
    category: "Serum",
    brand: "The Ordinary",
    name: "Alpha Arbutin 2% + HA",
    volume: "30ml",
    retailPrice: 19.07,
    description: "Brightening and dark spot corrector with high relevance in sunny markets. Alpha arbutin targets hyperpigmentation while hyaluronic acid hydrates.",
    tags: ["Dark Spots", "Brightening", "Alpha Arbutin", "Hyperpigmentation"],
  },
  {
    id: 14,
    category: "Serum",
    brand: "SKIN1004",
    name: "Madagascar Centella Ampoule",
    volume: "100ml",
    retailPrice: 29.43,
    description: "Concentrated centella soothing ampoule trending for sensitive and reactive skin. Calms redness and strengthens the skin barrier.",
    tags: ["Centella", "Soothing", "Sensitive Skin", "Barrier"],
  },
  {
    id: 15,
    category: "Essence",
    brand: "mixsoon",
    name: "Bean Essence",
    volume: "50ml",
    retailPrice: 44.97,
    description: "Viral minimalist essence powered by soybean ferment extract. Clean beauty staple for deep nourishment and a healthy, luminous complexion.",
    tags: ["Clean Beauty", "Fermented", "Nourishing", "Minimalist"],
  },
  {
    id: 16,
    category: "Toner",
    brand: "Anua",
    name: "Heartleaf 77% Soothing Toner",
    volume: "250ml",
    retailPrice: 34.32,
    description: "Fastest rising K-beauty toner 2024-25. 77% heartleaf extract calms irritated skin and prepares it to absorb subsequent skincare steps.",
    tags: ["Heartleaf", "Soothing", "Calming", "K-Beauty"],
  },
  {
    id: 17,
    category: "Toner",
    brand: "I'm from",
    name: "Rice Toner",
    volume: "150ml",
    retailPrice: 44.97,
    description: "#glassskin viral toner with a natural rice ingredient story. Fermented rice water brightens and smooths skin texture for a poreless finish.",
    tags: ["Rice Extract", "Glass Skin", "Brightening", "Smoothing"],
  },
  {
    id: 18,
    category: "Cream",
    brand: "COSRX",
    name: "Advanced Snail 92 All In One Cream",
    volume: "100g",
    retailPrice: 33.12,
    description: "Iconic cult cream and global K-beauty staple. 92% snail secretion filtrate heals, hydrates, and smooths all in one step.",
    tags: ["Snail Mucin", "All-in-One", "Healing", "Cult Classic"],
  },
  {
    id: 19,
    category: "Moisturizer",
    brand: "CeraVe",
    name: "Moisturizing Cream",
    volume: "340g",
    retailPrice: 28.60,
    description: "TikTok iconic moisturizing tub. Consistently top-3 global skincare with ceramides and hyaluronic acid for 24-hour hydration.",
    tags: ["Ceramides", "24H Hydration", "Dermatologist", "Bestseller"],
  },
  {
    id: 20,
    category: "Moisturizer",
    brand: "Dr Althea",
    name: "147 Barrier Cream",
    volume: "50ml",
    retailPrice: 39.68,
    description: "Clinical barrier repair cream with dermatology-adjacent brand positioning. Strengthens and restores the skin's protective barrier.",
    tags: ["Barrier Repair", "Clinical", "Soothing", "Protective"],
  },
  {
    id: 21,
    category: "Cleanser",
    brand: "COSRX",
    name: "Low pH Good Morning Gel Cleanser",
    volume: "150ml",
    retailPrice: 31.05,
    description: "Best-selling K-beauty cleanser globally. pH-balanced formula maintains the skin's natural acid mantle for healthy, balanced skin.",
    tags: ["pH-Balanced", "Gel Cleanser", "Bestseller", "K-Beauty"],
  },
  {
    id: 22,
    category: "Cleanser",
    brand: "CeraVe",
    name: "Foaming Facial Cleanser",
    volume: "236ml",
    retailPrice: 21.80,
    description: "Dermatologist #1 cleanser globally with consistent demand. Removes dirt, oil, and makeup while maintaining the skin's moisture balance.",
    tags: ["Foaming", "Dermatologist", "Ceramides", "Gentle"],
  },
  {
    id: 23,
    category: "Cleanser",
    brand: "Anua",
    name: "Heartleaf Pore Control Cleansing Oil",
    volume: "200ml",
    retailPrice: 40.86,
    description: "Top cleansing oil in K-beauty for pore-minimizing results. Melts makeup and sunscreen while heartleaf extract soothes the skin.",
    tags: ["Cleansing Oil", "Pore Care", "Makeup Removal", "Heartleaf"],
  },
  {
    id: 24,
    category: "Cleanser",
    brand: "SKIN1004",
    name: "Madagascar Centella Ampoule Foam",
    volume: "125ml",
    retailPrice: 27.47,
    description: "Gentle centella foam cleanser popular with sensitive skin. Rich foam lifts impurities while centella calms and soothes reactive skin.",
    tags: ["Gentle", "Centella", "Sensitive Skin", "Foam"],
  },
  {
    id: 25,
    category: "Treatment",
    brand: "La Roche-Posay",
    name: "Effaclar Duo+ Acne Treatment SPF30",
    volume: "40ml",
    retailPrice: 27.25,
    description: "Global acne pharmacy #1 with consistent dermatologist demand. Targets breakouts while SPF 30 protects skin from sun damage.",
    tags: ["Acne", "SPF 30", "Dermatologist", "Blemish Control"],
  },
  {
    id: 26,
    category: "Treatment",
    brand: "COSRX",
    name: "BHA Blackhead Power Liquid",
    volume: "100ml",
    retailPrice: 31.05,
    description: "Holy-grail exfoliant recommended by dermatologists globally. BHA (betaine salicylate) dissolves blackheads and unclogs pores effectively.",
    tags: ["BHA", "Exfoliant", "Blackheads", "Pore Care"],
  },
  {
    id: 27,
    category: "Treatment",
    brand: "medicube",
    name: "PDRN Booster Gel",
    volume: "300ml",
    retailPrice: 35.87,
    description: "Cutting-edge PDRN (Polydeoxyribonucleotide) ingredient for clinical skin repair. The same regenerative ingredient used in medical aesthetics.",
    tags: ["PDRN", "Clinical", "Regenerating", "Innovative"],
  },
  {
    id: 28,
    category: "Patch",
    brand: "COSRX",
    name: "Acne Pimple Master Patch",
    volume: "24 patches",
    retailPrice: 24.42,
    description: "Over 1 billion patches sold globally. Hydrocolloid technology draws out impurities overnight for faster healing without scarring.",
    tags: ["Hydrocolloid", "Acne Patch", "Bestseller", "Overnight"],
  },
  {
    id: 29,
    category: "Eye Patch",
    brand: "JAYJUN",
    name: "Green Tea Eye Gel Patch",
    volume: "60 patches",
    retailPrice: 38.92,
    description: "K-beauty specialty eye patches for the self-care and gifting segment. Green tea antioxidants reduce puffiness and dark circles.",
    tags: ["Eye Care", "Green Tea", "De-Puffing", "Gifting"],
  },
  {
    id: 30,
    category: "Serum",
    brand: "COSRX",
    name: "The Vitamin C 23 Serum",
    volume: "20ml",
    retailPrice: 31.05,
    description: "Vitamin C brightening serum with high demand in sun-exposed markets. 23% pure vitamin C targets dark spots and protects against UV-induced damage.",
    tags: ["Vitamin C", "Brightening", "Dark Spots", "Antioxidant"],
  },
];

export const categories = [
  "All",
  "SPF",
  "Serum",
  "Essence",
  "Toner",
  "Cream",
  "Moisturizer",
  "Cleanser",
  "Treatment",
  "Patch",
  "Eye Patch",
];
