export interface Product {
  id: number;
  category: string;
  brand: string;
  name: string;
  volume: string;
  retailPrice: number;
  description: string;
  tags: string[];
  stock: number;
  images?: string[];
}

// Metro requires static require() calls, so every product image is registered here
// and referenced by key from lib/products.ts instead of a dynamic path string.
export const productImages: Record<string, ReturnType<typeof require>> = {
  "anua-heartleaf-cleansing-oil-1": require("../assets/products/anua-heartleaf-cleansing-oil-1.jpg"),
  "anua-heartleaf-toner-1": require("../assets/products/anua-heartleaf-toner-1.jpg"),
  "boj-glow-deep-serum-1": require("../assets/products/boj-glow-deep-serum-1.jpg"),
  "boj-relief-sun-1": require("../assets/products/boj-relief-sun-1.jpg"),
  "boj-relief-sun-2": require("../assets/products/boj-relief-sun-2.jpg"),
  "boj-relief-sun-3": require("../assets/products/boj-relief-sun-3.jpg"),
  "cerave-hydrating-cleanser-1": require("../assets/products/cerave-hydrating-cleanser-1.jpg"),
  "cerave-moisturising-cream-1": require("../assets/products/cerave-moisturising-cream-1.jpg"),
  "cosrx-snail-cream-1": require("../assets/products/cosrx-snail-cream-1.jpg"),
  "isntree-hyaluronic-sun-gel-1": require("../assets/products/isntree-hyaluronic-sun-gel-1.jpg"),
  "lrp-anthelios-uvmune400-1": require("../assets/products/lrp-anthelios-uvmune400-1.jpg"),
  "medicube-pdrn-serum-1": require("../assets/products/medicube-pdrn-serum-1.jpg"),
  "ordinary-niacinamide-1": require("../assets/products/ordinary-niacinamide-1.jpg"),
  "skin1004-centella-ampoule-1": require("../assets/products/skin1004-centella-ampoule-1.jpg"),
  "skin1004-centella-toner-1": require("../assets/products/skin1004-centella-toner-1.jpg"),
};

// Prices = wholesale cost (AED ÷ 3.6725) + 35% margin.
// Stock = opening order quantities.
export const products: Product[] = [
  {
    id: 1,
    category: "Cleanser",
    brand: "Anua",
    name: "Heartleaf Pore Control Cleansing Oil",
    volume: "200ml",
    retailPrice: 18.38,
    description: "Top cleansing oil in K-beauty for pore-minimizing results. Melts away makeup, sunscreen, and excess sebum while heartleaf extract soothes the skin. The first step of a proper double cleanse.",
    tags: ["Cleansing Oil", "Pore Care", "Makeup Removal", "Heartleaf"],
    stock: 10,
    images: ["anua-heartleaf-cleansing-oil-1"],
  },
  {
    id: 2,
    category: "Cleanser",
    brand: "CeraVe",
    name: "Hydrating Cleanser",
    volume: "236ml",
    retailPrice: 11.76,
    description: "Dermatologist-developed gentle cleanser with ceramides and hyaluronic acid. Cleanses without stripping moisture — ideal for normal to dry skin and daily use.",
    tags: ["Gentle", "Ceramides", "Dermatologist", "Hydrating"],
    stock: 12,
    images: ["cerave-hydrating-cleanser-1"],
  },
  {
    id: 3,
    category: "Toner",
    brand: "Anua",
    name: "Heartleaf 77% Soothing Toner",
    volume: "250ml",
    retailPrice: 20.22,
    description: "Fastest rising K-beauty toner. 77% heartleaf extract calms irritated, sensitive skin and preps it to absorb the rest of your routine.",
    tags: ["Heartleaf", "Soothing", "Calming", "K-Beauty"],
    stock: 7,
    images: ["anua-heartleaf-toner-1"],
  },
  {
    id: 4,
    category: "Toner",
    brand: "SKIN1004",
    name: "Madagascar Centella Toning Toner",
    volume: "210ml",
    retailPrice: 20.22,
    description: "Mildly exfoliating daily toner with centella asiatica from Madagascar. Refines skin texture and calms redness in one step.",
    tags: ["Centella", "Texture", "Soothing", "Daily Toner"],
    stock: 3,
    images: ["skin1004-centella-toner-1"],
  },
  {
    id: 5,
    category: "Essence",
    brand: "COSRX",
    name: "Advanced Snail 96 Mucin Power Essence",
    volume: "100ml",
    retailPrice: 13.97,
    description: "Amazon #1 K-beauty essence with 200K+ reviews worldwide. 96% snail secretion filtrate repairs and hydrates for glass-skin results.",
    tags: ["Snail Mucin", "Repairing", "Bestseller", "Glass Skin"],
    stock: 18,
  },
  {
    id: 6,
    category: "Serum",
    brand: "The Ordinary",
    name: "Niacinamide 10% + Zinc 1%",
    volume: "30ml",
    retailPrice: 9.19,
    description: "#1 serum globally with unbeatable price-to-performance. Minimizes pores, controls oil, and fades dark spots and hyperpigmentation.",
    tags: ["Niacinamide", "Pore Care", "Brightening", "Oil Control"],
    stock: 18,
    images: ["ordinary-niacinamide-1"],
  },
  {
    id: 7,
    category: "Serum",
    brand: "Beauty of Joseon",
    name: "Glow Deep Serum: Rice + Arbutin",
    volume: "30ml",
    retailPrice: 13.97,
    description: "Viral K-beauty brightening serum. Rice bran water nourishes while alpha arbutin targets dark spots and uneven tone — perfect for sun-exposed skin.",
    tags: ["Brightening", "Rice", "Dark Spots", "K-Beauty"],
    stock: 10,
    images: ["boj-glow-deep-serum-1"],
  },
  {
    id: 8,
    category: "Serum",
    brand: "medicube",
    name: "PDRN Pink Peptide Serum",
    volume: "30ml",
    retailPrice: 16.54,
    description: "Trending clinical serum with PDRN and peptides for firmer, bouncier skin. The same regenerative ingredient used in medical aesthetics.",
    tags: ["PDRN", "Peptides", "Firming", "Trending"],
    stock: 7,
    images: ["medicube-pdrn-serum-1"],
  },
  {
    id: 9,
    category: "Serum",
    brand: "SKIN1004",
    name: "Madagascar Centella Ampoule",
    volume: "55ml",
    retailPrice: 15.44,
    description: "Concentrated centella soothing ampoule for sensitive and reactive skin. Calms redness and strengthens the skin barrier.",
    tags: ["Centella", "Soothing", "Sensitive Skin", "Barrier"],
    stock: 7,
    images: ["skin1004-centella-ampoule-1"],
  },
  {
    id: 10,
    category: "Moisturizer",
    brand: "COSRX",
    name: "Advanced Snail 92 All In One Cream",
    volume: "100g",
    retailPrice: 13.97,
    description: "Iconic cult cream and global K-beauty staple. 92% snail secretion filtrate heals, hydrates, and smooths all in one step.",
    tags: ["Snail Mucin", "All-in-One", "Healing", "Cult Classic"],
    stock: 10,
    images: ["cosrx-snail-cream-1"],
  },
  {
    id: 11,
    category: "Moisturizer",
    brand: "CeraVe",
    name: "Moisturising Cream (Tub)",
    volume: "454g",
    retailPrice: 11.76,
    description: "TikTok-famous moisturizing tub. Ceramides and hyaluronic acid deliver 24-hour hydration for face and body — unbeatable value in the big size.",
    tags: ["Ceramides", "24H Hydration", "Face & Body", "Value Size"],
    stock: 8,
    images: ["cerave-moisturising-cream-1"],
  },
  {
    id: 12,
    category: "SPF",
    brand: "Beauty of Joseon",
    name: "Relief Sun: Rice + Probiotics SPF50+ PA++++",
    volume: "50ml",
    retailPrice: 13.97,
    description: "Viral TikTok SPF #1 globally. No white cast, rice extract brightens while probiotics strengthen the skin barrier. Perfect for Somalia's high-UV climate.",
    tags: ["SPF 50+", "No White Cast", "K-Beauty", "Brightening"],
    stock: 18,
    images: ["boj-relief-sun-2", "boj-relief-sun-1", "boj-relief-sun-3"],
  },
  {
    id: 13,
    category: "SPF",
    brand: "Isntree",
    name: "Hyaluronic Acid Watery Sun Gel SPF50+",
    volume: "50ml",
    retailPrice: 16.54,
    description: "Lightweight watery gel sunscreen with 8 types of hyaluronic acid. Hydrating, no white cast, and comfortable in hot weather all day.",
    tags: ["SPF 50+", "Watery Gel", "Hyaluronic Acid", "Lightweight"],
    stock: 7,
    images: ["isntree-hyaluronic-sun-gel-1"],
  },
  {
    id: 14,
    category: "SPF",
    brand: "SKIN1004",
    name: "Centella Air-Fit Suncream Plus SPF50+",
    volume: "50ml",
    retailPrice: 15.44,
    description: "Air-light finish suncream with soothing centella. No stickiness, no white cast — protection that feels like nothing on the skin.",
    tags: ["SPF 50+", "Air-Light", "Centella", "No White Cast"],
    stock: 2,
  },
  {
    id: 15,
    category: "SPF",
    brand: "La Roche-Posay",
    name: "Anthelios UVMune 400 Invisible Fluid SPF50+",
    volume: "50ml",
    retailPrice: 13.97,
    description: "Dermatologist gold-standard SPF trusted globally. Invisible finish with advanced UVMune 400 technology for superior UV protection.",
    tags: ["SPF 50+", "Invisible", "Dermatologist", "Premium"],
    stock: 5,
    images: ["lrp-anthelios-uvmune400-1"],
  },
  {
    id: 16,
    category: "Treatment",
    brand: "The Ordinary",
    name: "AHA 30% + BHA 2% Peeling Solution",
    volume: "30ml",
    retailPrice: 9.19,
    description: "The famous red peeling mask. Weekly 10-minute exfoliating treatment that resurfaces skin for improved texture and radiance. For experienced users only.",
    tags: ["Exfoliant", "AHA/BHA", "Weekly Treatment", "Glow"],
    stock: 8,
  },
];

export const categories = [
  "All",
  "SPF",
  "Serum",
  "Essence",
  "Toner",
  "Cleanser",
  "Moisturizer",
  "Treatment",
];
